export const INTERNAL_DEFAULTS = {
  HEALTH_CHECK_TIMEOUT_MS: 5000,
  CROSS_SHARD_CONCURRENCY: 4,
  CROSS_SHARD_TIMEOUT_MS: 10000,
  CLI_COMMAND_TIMEOUT_MS: 120000,
  CLI_FORCE_KILL_GRACE_MS: 5000,
  CLI_MAX_OUTPUT_LENGTH: 1000000,
  CLI_TEST_TCP_TIMEOUT_MS: 5000,
  CLI_TEST_COMMAND_TIMEOUT_MS: 15000,
  STUDIO_BASE_PORT: 51212,
  STUDIO_REUSE_EXISTING: true,
  STUDIO_STRICT_PORT_CHECK: false,
  STUDIO_START_TIMEOUT_MS: 15000,
  STUDIO_STABILITY_MS: 500,
  STUDIO_SHUTDOWN_TIMEOUT_MS: 5000,
  STUDIO_PORT_SCAN_LIMIT: 100,
  /**
   * Studio queries one shard at a time. A small bound keeps a project with
   * many shards from accumulating a connection pool per database while still
   * making a switch back to a recent shard instant.
   */
  STUDIO_MAX_OPEN_CONNECTIONS: 3,
  STUDIO_IDLE_CONNECTION_TIMEOUT_MS: 60000,
} as const;
